# Generated by Django 3.0.6 on 2020-05-22 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('college', models.CharField(choices=[('CAS', 'College of Arts and Sciences'), ('CM', 'College of Medicine'), ('CD', 'College of Dentistry'), ('CAMP', 'College of Allied Medical Professions'), ('CP', 'College of Pharmacy'), ('CPH', 'College of Public Health')], max_length=200, null=True)),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('college', models.CharField(choices=[('CAS', 'College of Arts and Sciences'), ('CM', 'College of Medicine'), ('CD', 'College of Dentistry'), ('CAMP', 'College of Allied Medical Professions'), ('CP', 'College of Pharmacy'), ('CPH', 'College of Public Health')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('role', models.ManyToManyField(to='users.Role')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
