# Generated by Django 3.0.6 on 2020-05-22 11:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_tutor_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Profile',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
