# Generated by Django 3.0.6 on 2020-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='college',
            field=models.CharField(choices=[('CAS', 'College of Arts and Sciences'), ('CM', 'College of Medicine'), ('CD', 'College of Dentistry'), ('CAMP', 'College of Allied Medical Professions'), ('CP', 'College of Pharmacy'), ('CPH', 'College of Public Health')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='role',
            field=models.ManyToManyField(to='lrc.Role'),
        ),
    ]
